version: "3.8"
services: 
  vlc-vue-ui:
    container_name: vlc-vue-ui
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      - VLC_HOST=http://127.0.0.1
      - VLC_PORT=8080
    ports: 
      - 8081:80
